version: '3.8'

services:
  web:
    build: .
    # Проброс всей папки проекта целиком, чтобы файлы блокировок SQLite создавались корректно
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8080:8000"
    restart: always
