# Generated by Django 6.0.3 on 2026-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('presence', models.CharField(blank=True, choices=[('yes', 'да'), ('no', 'нет')], max_length=3)),
                ('plusone', models.CharField(blank=True, choices=[('yes', 'да'), ('no', 'нет')], max_length=3)),
                ('drink', models.TextField(blank=True)),
            ],
        ),
    ]
