# Generated by Django 6.0.5 on 2026-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='drink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='plusone',
            field=models.CharField(blank=True, choices=[('yes', 'да'), ('no', 'нет')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='presence',
            field=models.CharField(blank=True, choices=[('yes', 'да'), ('no', 'нет')], max_length=3, null=True),
        ),
    ]
